baseURL = 'http://yuan.fyi/'
languageCode = 'en-us'
title = "Yuan's Blog"
theme="beautifulhugo"

[Author]
  name = "Yinhuan Yuan"
  github = "yhyuan/yuan-blog-hugo"

[[menu.main]]
  name = 'Blog'
  url = ""
  weight = 1
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2
[[menu.main]]
  name = 'About'
  url = "pages/about"
  weight = 3

[outputs]
  home = ["HTML", "RSS", "JSON"]